// RootLayout.js
import Head from "next/head";
import { Inter } from "next/font/google"; // Correct the import path
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Easy Ride Car Rental",
  description: "Generated By Aon Pantheons",
};

const RootLayout = ({ children }) => {
  return (
    <>
      <Head>
        <html lang="en" />
      </Head>
      <body className={inter.className}>{children}</body>
    </>
  );
};

export default RootLayout;
