// RootLayout.js
import { Inter } from "next/font/google"; // Correct the import path
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Easy Ride Car Rental",
  description: "Generated By Aon Pantheons",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
};

export default RootLayout;
